### ISSUE TITLE
Expires date is wrongly displayed

### ISSUE THREAD

**Issue by vojtechsimetka** [rnsdomains/rns-manager-react#278]
In the domain administration, the expires date shows incorrect value
![Screenshot 2020-05-05 at 09 22 07](https://user-images.githubusercontent.com/7974813/81043303-50414880-8eb2-11ea-89b4-510971578c68.png)

**Comment by jessgusclark** [comment]
Hey @vojtechsimetka 

Let me look into your domain and see why you are getting this value. Did you originally buy it with the auction registrar? 

This is what it should look like:
![image](https://user-images.githubusercontent.com/766679/81093913-7515da00-8f0b-11ea-837e-bb16f83f8d92.png)

**Comment by vojtechsimetka** [comment]
@jessgusclark I did but I also went through some migration process later. It is good to know it's limited to me, I assumed everyone has wrong date there.
