### ISSUE TITLE
Every time I login to any domain it appears the "expired domain" screen for just 1 second

### ISSUE THREAD

**Issue by miltonwg** [rnsdomains/rns-manager-react#336]
Every time I login to any domain it appears the "expired domain" screen for just 1 second:
<img width="872" alt="Screen Shot 2020-08-10 at 10 47 31" src="https://user-images.githubusercontent.com/5920311/89789630-39387500-daf7-11ea-8d5a-ecd147bf6d2a.png">

**Comment by jessgusclark** [comment]
Closed with PR #352
