### ISSUE TITLE
In the *Search* section it shouldn't be requested to input the domain in lowercase

### ISSUE THREAD

**Issue by miltonwg** [rnsdomains/rns-manager-react#337]
In the **Search** section it shouldn't be requested to input in lowercase.
If the user doesn't read the error message, ge may think there's an error in the website.
Also, the site is forcing the user for an unnecessary extra step of lower casing (in mobile is  annoying).
The user shouldn't be stopped in this screen.

**Proposed solution:**
Whatever case the user uses as input the site should take it. In the back, the search should be done automatically in lowercase.
If the user wants to register, the site should show the domain in lowecase in the next screen.
There also could be a warning message "The domain will be registered in lowe case. Upper case domains are not valid." (or something like that.

![imagen](https://user-images.githubusercontent.com/5920311/89789699-510ff900-daf7-11ea-9950-da227a921c7f.png)

**Comment by jessgusclark** [comment]
References #251
