### ISSUE TITLE
Move the "logout" button to the bottom of the login popup (+ invert colors)

### ISSUE THREAD

**Issue by miltonwg** [rnsdomains/rns-manager-react#358]
I think the UX will be improved if the logout button goes to the bottom.
At this moment it is really close to the selected domain and can make the user press it by mistake.

Also, it could be painted in grey.
And paint in blue the selected domain (more relevant).

Here is the proposal:

![image](https://user-images.githubusercontent.com/5920311/101680490-8b56bc00-3a3f-11eb-93a7-3ad1f6c8180b.png)

**Comment by jessgusclark** [comment]
This comment was posted on #360 by mistake:

> Handle the two options of "logging out":
>
> 1. removing an item from localStorage, and takes you back to the home
> 2. logging out of the wallet completely
>
> Change the bottom button to say "Disconnect". It will leave all localStorage items but will disconnect the wallet. Then, next to each item, there should be a minus or x to remove the item from localStorage.
