### ISSUE TITLE
RNS Manager not working in dapp browsers (eg: rWallet)

### ISSUE THREAD

**Issue by miltonwg** [rnsdomains/rns-manager-react#360]
RNS Manager does not connect when entering from a mobile wallet's dapp browser.
It offers the web3 rlogin popup and when you press it it shows an error of selected network.

This used to work in the past.

Tested in [rWallet, production version](https://play.google.com/store/apps/details?id=com.rsk.rwallet.reactnative) and DCENT, experimental version.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/5920311/103362880-8b733600-4a98-11eb-9e19-1b78cf457baf.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/5920311/103362927-a645aa80-4a98-11eb-82e6-18de2738a50b.png">

**Comment by jessgusclark** [comment]
The in-app browser is returning an invalid response for chainId. We need to troubleshoot what response is returned from the in-app provider.

![Screenshot_20210104-172324_RWallet](https://user-images.githubusercontent.com/766679/103558922-0afc6d00-4ebe-11eb-8dbc-21b29be066a6.jpg)

**Comment by jessgusclark** [comment]
There are two "logging out":

1. removing an item from localStorage, and takes you back to the home
2. logging out of the wallet completely

**Comment by jessgusclark** [comment]
This was an issue with the rLogin Dapp Browser. It will be resolved when this PR is merged, https://github.com/rsksmart/rwallet/pull/653 and then deployed.

I'm going to mark this issues as complete.
