### ISSUE TITLE
Content should support any string

### ISSUE THREAD

**Issue by vojtechsimetka** [rnsdomains/rns-manager-react#6]
The content record should support string that is not prefixed with 0x. It should be able to at least use different protocols like `ipfs://` or `bzz://` similarly to ENS.

### RNS admin:
<img width="938" alt="Screenshot 2019-05-28 at 19 32 04" src="https://user-images.githubusercontent.com/7974813/58498996-78430a80-817f-11e9-9362-64591bea5649.png">

### ENS admin:
<img width="798" alt="Screenshot 2019-05-28 at 19 33 48" src="https://user-images.githubusercontent.com/7974813/58499021-88f38080-817f-11e9-9401-2dba1fe3e7e4.png">

**Comment by pmprete** [comment]
Same problem, it's a bit annoying to keep adding the 0x value all the time

**Comment by ilanolkies** [comment]
This is due to the RNS Public Resolver parameter, that is of type `bytes`.
I will move this issue to `rns-artifacts` to push this smart contract creation.

**Comment by ilanolkies** [comment]
https://github.com/rnsdomains/rns-artifacts/issues/12
